/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrocliente;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tamires Pires
 */
public class TelaPrincipal extends javax.swing.JFrame {
        
    private int cookie = 0;
    private int clickUpgradeValue = 25;
    private int autoClickUpgradeValue = 50;
    private int clickCookie = 1;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        click = new javax.swing.JButton();
        clickLabel = new javax.swing.JLabel();
        upgradeClickButton = new javax.swing.JButton();
        valueOfUpgradeClick = new javax.swing.JLabel();
        autoMoneyUpgrade = new javax.swing.JButton();
        valueOfAutoMoneyUpgrade = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        click.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        click.setText("Click");
        click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickMouseClicked(evt);
            }
        });
        click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });

        clickLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clickLabel.setText("Money: 0");
        clickLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                clickLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        upgradeClickButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        upgradeClickButton.setText("Upgrade Click +1");
        upgradeClickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upgradeClickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeClickButtonMouseClicked(evt);
            }
        });
        upgradeClickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeClickButtonActionPerformed(evt);
            }
        });

        valueOfUpgradeClick.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valueOfUpgradeClick.setText("25$");
        valueOfUpgradeClick.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                valueOfUpgradeClickAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        autoMoneyUpgrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        autoMoneyUpgrade.setText("Upgrade Auto Money +1");
        autoMoneyUpgrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        autoMoneyUpgrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoMoneyUpgradeMouseClicked(evt);
            }
        });
        autoMoneyUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMoneyUpgradeActionPerformed(evt);
            }
        });

        valueOfAutoMoneyUpgrade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valueOfAutoMoneyUpgrade.setText("50$");
        valueOfAutoMoneyUpgrade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        valueOfAutoMoneyUpgrade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                valueOfAutoMoneyUpgradeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu1.setText("Option");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clickLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                        .addComponent(upgradeClickButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueOfUpgradeClick))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(autoMoneyUpgrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueOfAutoMoneyUpgrade)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueOfUpgradeClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(upgradeClickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueOfAutoMoneyUpgrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(autoMoneyUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198)
                .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Deseja sair da aplicação?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
   
    }//GEN-LAST:event_clickActionPerformed

    private void clickLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_clickLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_clickLabelAncestorAdded

    private void clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseClicked
        this.cookie = this.cookie + this.clickCookie;
        
        clickLabel.setText("Money: " + this.cookie);
    }//GEN-LAST:event_clickMouseClicked

    private void upgradeClickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeClickButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upgradeClickButtonActionPerformed

    private void upgradeClickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeClickButtonMouseClicked
        if(this.clickUpgradeValue > this.cookie) {
        JOptionPane.showMessageDialog(null, "Você não tem dinheiro suficiente para realizar esse upgrade", "upgrade click", JOptionPane.INFORMATION_MESSAGE);
        } else if(this.clickUpgradeValue <= this.cookie) {
        this.cookie = this.cookie - this.clickUpgradeValue;
        clickLabel.setText("Money: " + this.cookie);
        
        this.clickCookie++;
        this.clickUpgradeValue *= 1.5;
        valueOfUpgradeClick.setText(this.clickUpgradeValue + "$");
        }
    }//GEN-LAST:event_upgradeClickButtonMouseClicked

    private void valueOfUpgradeClickAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_valueOfUpgradeClickAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_valueOfUpgradeClickAncestorAdded

    private void autoMoneyUpgradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoMoneyUpgradeMouseClicked
        
        if(autoClickUpgradeValue > cookie) {
            JOptionPane.showMessageDialog(null, "Você não tem dinheiro suficiente para realizar esse upgrade", "upgrade click", JOptionPane.INFORMATION_MESSAGE);
        } else if (autoClickUpgradeValue <= cookie) {
            cookie = cookie - autoClickUpgradeValue;
            
            clickLabel.setText("Money: " + this.cookie);
            autoClickUpgradeValue *= 1.5;
            valueOfAutoMoneyUpgrade.setText(autoClickUpgradeValue + "$");
            
            int cont = 0;
            cont++;
            
            timerMoney(cont);
        }
    }//GEN-LAST:event_autoMoneyUpgradeMouseClicked

    private void timerMoney(int cont) {
    
        Timer timer = new Timer();
        
        Long delay = (1000 * 2l);
        
        TimerTask addMoney = new TimerTask() {
            @Override
            public void run() {
                cookie = cookie + cont;
                clickLabel.setText("Money: " + cookie);
            }
        };
    
        timer.scheduleAtFixedRate(addMoney, 0, delay);
        
    }
    
    
    
    private void autoMoneyUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMoneyUpgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoMoneyUpgradeActionPerformed

    private void valueOfAutoMoneyUpgradeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_valueOfAutoMoneyUpgradeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_valueOfAutoMoneyUpgradeAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoMoneyUpgrade;
    private javax.swing.JButton click;
    private javax.swing.JLabel clickLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JButton upgradeClickButton;
    private javax.swing.JLabel valueOfAutoMoneyUpgrade;
    private javax.swing.JLabel valueOfUpgradeClick;
    // End of variables declaration//GEN-END:variables
}
